name: Release
on:
  push:
    tags:
      - v*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Get version tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@master
      # Alpha branch
      - name: Publish alpha
        if: github.event.base_ref == 'refs/heads/alpha'
        run: |
          SEMVER=${{ steps.previoustag.outputs.tag }}
          RELEASE_VERSION="${SEMVER:1}"
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.CONTAINER_REGISTRY_PAT }}
          docker build --build-arg RELEASE_VERSION=$RELEASE_VERSION -f OctoMedia.Api/Dockerfile -t ghcr.io/jh12/octomedia.api/octomedia.api:latest-alpha -t ghcr.io/jh12/octomedia.api/octomedia.api:$RELEASE_VERSION .
          docker push --all-tags ghcr.io/jh12/octomedia.api/octomedia.api
          docker logout ghcr.io
          #dotnet pack ./OctoMedia.Api.DTOs/OctoMedia.Api.DTOs.csproj --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -p:PackageVersion=$RELEASE_VERSION
          #dotnet nuget push **/*.nupkg --source "https://nuget.pkg.github.com/jh12/index.json" --api-key ${{ secrets.CONTAINER_REGISTRY_PAT }}
      # Master branch
      - name: Publish master
        if: github.event.base_ref == 'refs/heads/master'
        run: |
          SEMVER=${{ steps.previoustag.outputs.tag }}
          RELEASE_VERSION="${SEMVER:1}"
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.CONTAINER_REGISTRY_PAT }}
          docker build --build-arg RELEASE_VERSION=$RELEASE_VERSION -f OctoMedia.Api/Dockerfile -t ghcr.io/jh12/octomedia.api/octomedia.api:latest -t ghcr.io/jh12/octomedia.api/octomedia.api:$RELEASE_VERSION .
          docker push --all-tags ghcr.io/jh12/octomedia.api/octomedia.api
          docker logout ghcr.io
          #dotnet pack ./OctoMedia.Api.DTOs/OctoMedia.Api.DTOs.csproj --configuration Release --include-symbols -p:SymbolPackageFormat=snupkg -p:PackageVersion=$RELEASE_VERSION
          #dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SOURCE }}
